#!/bin/bash

echo 'Executing rust script'

sudo apt update
sudo apt install build-essential curl pkg-config libssl-dev

curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh

source $HOME/.cargo/env
